language: node_js
node_js:
  - 12 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "graceshopper-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: graceshopper30
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: NQE/SmVeX3lkyis0j2RAS5gCekURv5Ge4RcwWnzyuPUkRnp4P62KrhxblB6ppAIwC7rY/2l36LVyo9+lhDtaPz4C40B/HynIdT3cSG8ktOf5KdkW9uyJhtAT5S8yavIZ0pNbikszxqOlbaZ6hBlrHvItdK3v+y2h9g9BuZwPYifNJ3/KVnm6ujzCbRSWHM56GJ9Wr7ImO2qDb88/CGHbuEsAK7mPCd59HcnOriLTcRlOMnetr8mqFLS6uI2nohoqLTcobWJgGEy6nG7QAnCKtxN8Ko5tVBsjR76IrwS/yrc+Mt7HW1lkarBAaC7xk862BWHN878gzhhHWBLop2nI4wKQo2JVsuuwKwycpoANymyqh4k/4Ry06zmWKSnwmpinkYXBIV27DwkJOA5wmGFx8lZclEQxT4UhdD6bMmaBnWVtvMVZ1c8ZyxHTcgin72alG3VSthroSVMp/UdvnQLmR/3wA2KnOXbUUsIAYwBMfRcetKdyz8RANKlGbpglKBHJxtAO4YtchLyroFIYNownfa3anI8tzyfcjHWkNxpV3UsoXHIxhaw2dwVs/u09YQge9MMagOj6RKElYjyMiyUmC1SPSCtEZMDG40CxU3/iOwV4hB1dImrZOJJiwBMZrt1TpOwwfePeVNewNz7W67r87xublz8MGOMm8wBh8pPvZBo=
